### PR TITLE
chore: Refactor code quality issues

### PR DESCRIPTION
**Pull request by ankitdobhal**
## Description
Hey 👋 , I'm member of the Developer Outreach team at DeepSource and ran DeepSource analysis on my fork of the repo. It found some interesting [code quality improvements](https://deepsource.io/gh/ankitdobhal/gev/issues) to consider.

This PR fixes a few of the issues detected for you to assess if it is right for you.
Happy to provide the tweaks separately otherwise :)

## Important changes

- Fix check for empty string
- Remove unnecessary use of slice
- Added .deepsource.toml file for continuous analysis on bug risks/performance/code-quality issues

## Type of change

- [x] Antipattern
- [ ] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

### CODE REVIEW

**Comment by Allenxuxu** [comment]
Thanks 🥳

**Comment by ankitdobhal** [comment]
Thanks @Allenxuxu   !
Activating analysis will help you to continuously analyze repo for code quality issues and fix commonly occurring issues using the auto-fix feature. 

To activate [DeepSource](https://deepsource.io/) you just need to follow these small steps:

- Install DeepSource on your repository [here](https://deepsource.io/signup).
- create .deepsource.toml configuration which you can use to configure your analysis settings.
> Note: This PR already have .deepsource.toml file so after merging you don't to create this one.
- Activate analysis [here](https://deepsource.io/gh/Allenxuxu/gev/issues)

**Comment by ankitdobhal** [comment]
> Thanks @Allenxuxu !
> Activating analysis will help you to continuously analyze repo for code quality issues and fix commonly occurring issues using the auto-fix feature.
> 
> To activate [DeepSource](https://deepsource.io/) you just need to follow these small steps:
> 
> * Install DeepSource on your repository [here](https://deepsource.io/signup).
> * create .deepsource.toml configuration which you can use to configure your analysis settings.
> 
> > Note: This PR already have .deepsource.toml file so after merging you don't need to create this one.
> 
> * Activate analysis [here](https://deepsource.io/gh/Allenxuxu/gev/issues)

hey @Allenxuxu , please have a look.

**Comment by Allenxuxu** [comment]
> > Thanks @Allenxuxu !
> > Activating analysis will help you to continuously analyze repo for code quality issues and fix commonly occurring issues using the auto-fix feature.
> > To activate [DeepSource](https://deepsource.io/) you just need to follow these small steps:
> > 
> > * Install DeepSource on your repository [here](https://deepsource.io/signup).
> > * create .deepsource.toml configuration which you can use to configure your analysis settings.
> > 
> > > Note: This PR already have .deepsource.toml file so after merging you don't need to create this one.
> > 
> > 
> > 
> > * Activate analysis [here](https://deepsource.io/gh/Allenxuxu/gev/issues)
> 
> hey @Allenxuxu , please have a look.

image
I have installed it, but there seems to be something wrong

**Comment by ankitdobhal** [comment]
> > > Thanks @Allenxuxu !
> > > Activating analysis will help you to continuously analyze repo for code quality issues and fix commonly occurring issues using the auto-fix feature.
> > > To activate [DeepSource](https://deepsource.io/) you just need to follow these small steps:
> > > 
> > > * Install DeepSource on your repository [here](https://deepsource.io/signup).
> > > * create .deepsource.toml configuration which you can use to configure your analysis settings.
> > > 
> > > > Note: This PR already have .deepsource.toml file so after merging you don't need to create this one.
> > > 
> > > 
> > > 
> > > * Activate analysis [here](https://deepsource.io/gh/Allenxuxu/gev/issues)
> > 
> > 
> > hey @Allenxuxu , please have a look.
> 
> image
> I have installed it, but there seems to be something wrong

Hey @Allenxuxu !
To activate analysis go to `settings` > `click on  Activate Analysis`.
Screenshot from 2021-04-05 01-36-06

**Comment by Allenxuxu** [comment]
@ankitdobhal It works now. Thanks 🥳

**Pull request merged**
